name: My First Workflow

on: [push, fork]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v6.0.1

    - name: Use SHA in a command
      run: echo "The commit SHA is $GITHUB_SHA"

    - name: Welcome message
      run: echo "My First GitHub Action Job"
    
    - name: List files
      run: ls

    - name: Read file
      run: cat README.md

